server:
  port: 7082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    org: debug



spring:
  application:
    name: api-gateway

  devtools:
    livereload:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          gateway:
            client-id: hairless-gateway
            client-secret: pw
            client-name: Hairless
            scope: ui
            provider: custom-provider
            redirect-uri: http://hairless.ljqiii.xyz:7082/login/oauth2/code/gateway
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://hairless.ljqiii.xyz:7081/oauth/token
            authorization-uri: http://hairless.ljqiii.xyz:7081/oauth/authorize
            user-info-uri: http://hairless.ljqiii.xyz:7081/userinfo
            user-name-attribute: name

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-server
          uri: http://127.0.0.1:7081
          predicates:
            - Path=/auth/**
          filters:
            - TokenRelay=
            - StripPrefix=1

        - id: point-service
          uri: http://127.0.0.1:7083
          predicates:
            - Path=/api/point/**
          filters:
            - TokenRelay=
            - StripPrefix=2

        - id: dockerjudge-service
          uri: http://127.0.0.1:7084
          predicates:
            - Path=/api/judge/**
          filters:
            - TokenRelay=
            - StripPrefix=2

        - id: notification-service
          uri: http://127.0.0.1:7085
          predicates:
            - Path=/api/notification/**
          filters:
            - TokenRelay=
            - StripPrefix=2

        - id: account-service
          uri: http://127.0.0.1:7086
          predicates:
            - Path=/api/account/**
          filters:
            - TokenRelay=
            - StripPrefix=2

        - id: hairless-main
          uri: http://127.0.0.1:7087
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - StripPrefix=1


        - id: hairless-vue
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/**





#
#  filter:
#        remove-non-proxy-headers:
#          headers: