spring:
  application:
    name: eureka
server:
  port: 8761


eureka:
  server:
    eviction-interval-timer-in-ms: 2000
    responseCacheUpdateIntervalMs: 2000
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 2
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/


